% =========================================================================
% Copyright (c) 2008-2014 Audio Communication Group, TU Berlin
% 
% This file is part of WhisPER, a package of interacting MATLAB scripts for 
% designing and controlling experiments in the field of auditory perceptive 
% measurement and evaluation.
% 
% WhisPER is free software: you can redistribute it and/or modify it under 
% the terms of the GNU General Public License as published by the Free 
% Software Foundation, either version 3 of the License, or (at your option) 
% any later version. 
% 
% WhisPER is distributed in the hope that it will be useful, but WITHOUT ANY 
% WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
% FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License along 
% with this program. If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.ak.tu-berlin.de/whisper/ 
% =========================================================================
% 
% This file:
%
% Author :   Martina Vrhovnik and Fabian Brinkmann,
%            Audio Communication Group, TU Berlin
% Email  :   fabian.brinkmann at tu-berlin dot de
% Date   :   Oct. 2013
% Updated: 
%             
% =========================================================================

SAQI_phrases = ...
    {...
     1 {{'Is there a noticeable difference between the two stimuli?';'If there is, please rate perceived amount of this difference.'};... 
       {'Does stimulus A differ from your expectations?';'If there is, please rate the perceived amount of this difference.'}};... 
     2 'Please rate:';...
     3 'Is the perceived difference ...';...
     4 '... constant in time?';...
     5 '... varying periodically or otherwise rule-based?';...
     6 '... varying non-regularly?';...
     7 '... continuously?';...
     8 '... discontinuously?';...
     9 'Does the perceived difference depend on ...';...
     10 '... your actions?';...
     11 '... scene events?';...
     12 '... nothing of the before mentioned?';...
     13 'Which of the following entities would you assign the perceived difference to (multiple selections possible)?';...
     14 {{'Did you perceive any other difference not mentioned before?';'If so, please name and rate the perceived amount of this difference.'};...
        {'Does stimulus A differ from your expectations in any other way not mentioned before?';'If so, please name and rate the perceived amount of this difference.'}};...
     15 'Please name the difference';...
     16 'up to 180';...
     };
