% =========================================================================
% Copyright (c) 2008-2014 Audio Communication Group, TU Berlin
% 
% This file is part of WhisPER, a package of interacting MATLAB scripts for 
% designing and controlling experiments in the field of auditory perceptive 
% measurement and evaluation.
% 
% WhisPER is free software: you can redistribute it and/or modify it under 
% the terms of the GNU General Public License as published by the Free 
% Software Foundation, either version 3 of the License, or (at your option) 
% any later version. 
% 
% WhisPER is distributed in the hope that it will be useful, but WITHOUT ANY 
% WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
% FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License along 
% with this program. If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.ak.tu-berlin.de/whisper/ 
% =========================================================================
% 
% This file:
%
% Author :   Martina Vrhovnik and Fabian Brinkmann,
%            Audio Communication Group, TU Berlin
% Email  :   fabian.brinkmann at tu-berlin dot de
% Date   :   Oct. 2013
% Updated: 
%             
% =========================================================================

SAQI_phrases = ...
    {...
     1 {{['K' char(246) 'nnen Sie zwischen den beiden Stimuli einen Unterschied wahrnehmen?'];['Wenn ja, bewerten Sie bitte die Auspr' char(228) 'gung des wahrgenommenen Unterschieds.']};... 
       {'Unterscheidet sich Stimulus A von Ihrer Erwartung?';['Wenn ja, bewerten Sie bitte die Auspr' char(228) 'gung des wahrgenommenen Unterschieds!']}};... 
     2 'Bewerten Sie:';...
     3 'Ist der wahrgenommene Unterschied...';...
     4 '... konstant?';...
     5 ['... regelhaft zeitver' char(228) 'nderlich?'];...
     6 ['... regellos zeitver' char(228) 'nderlich?'];...
     7 '... und dabei stetig?';...
     8 '... und dabei unstetig?';...
     9 ['Ist der wahrgenommene Unterschied ab' char(228) 'hngig von...'];...
     10 '... Ihren Reaktionen?';...
     11 '... Ereignissen in der Szene?';...
     12 '... keinem davon.';...
     13 ['Welchem der folgenden Objekte (oder auch mehreren davon) w' char(252) 'rden Sie den wahrgenommenen Unterschied zuordnen?'];...
     14 {{['K' char(246) 'nnen Sie zwischen den beiden Stimuli sonst noch einen Unterschied wahrnehmen?'];['Wenn ja, benennen und bewerten Sie die Auspr' char(228) 'gung der Qualit' char(228) 't.']};...
        {'Unterscheidet sich Stimulus A in einer sonstigen Weise von Ihrer Erwartung?';['Wenn ja, benennen und bewerten Sie die Auspr' char(228) 'gung der Quali' char(228) 'tt.']}};...
     15 'Benennen Sie den Unterschied';...
     16 'bis 180';...
     };





